apiVersion: v1
kind: Service
metadata:
  namespace: multitenant-cms
  name: app-service
  labels:
    app: app-service
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 80
  selector:
    app: app
  type: ClusterIP
