apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: multitenant-cms
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
