apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: multitenant-cms
  name: cache
spec:
  serviceName: cache
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: TZ
              value: "Asia/Tokyo"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
