apiVersion: v1
kind: Service
metadata:
  namespace: multitenant-cms
  name: cache-service
  labels:
    app: cache-service
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 6379
      targetPort: 6379
  selector:
    app: cache
