apiVersion: v1
kind: ConfigMap
metadata:
  namespace: multitenant-menu
  name: app-config-map
data:
  DB_CONNECTION: mysql
  DB_HOST: db-service.multitenant-menu.svc.cluster.local
  DB_PORT: "3306"
  DB_DATABASE: multitenant-menu
  DB_USERNAME: multitenant-menu
  DB_PASSWORD: password

  AUTH_DB_HOST: db-service.multitenant-auth.svc.cluster.local
  AUTH_DB_PORT: "3306"
  AUTH_DB_DATABASE: multitenant-auth
  AUTH_DB_USERNAME: multitenant-auth
  AUTH_DB_PASSWORD: password

  REDIS_CLIENT: phpredis
  REDIS_HOST: cache-service.multitenant-menu.svc.cluster.local
  REDIS_PASSWORD: null
  REDIS_PORT: "6379"

  AUTH_API_URL: app-service.multitenant-auth.svc.cluster.local:8000
