apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitenant-auth
  labels:
    app: multitenant-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitenant-auth
  template:
    metadata:
      labels:
        app: multitenant-auth
    spec:
      initContainers:
        - name: copy-auth-php-code
          image: php-mt-auth-k8:latest
          imagePullPolicy: Never
          command: ["sh", "-c", "cp -r /var/www/. /app"]
          volumeMounts:
            - name: app
              mountPath: /app
      containers:
        - name: multitenant-auth-php
          image: php-mt-auth-k8:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: app
              mountPath: /var/www
          env:
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: multitenant-auth-deployment-config-map
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: multitenant-auth-deployment-config-map
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: multitenant-auth-deployment-config-map
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: multitenant-auth-deployment-config-map
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: multitenant-auth-db-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: multitenant-auth-db-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
        - name: multitenant-auth-nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: multitenant-auth-nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
            - name: app
              mountPath: /var/www
              readOnly: true
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
      volumes:
        - name: app
          emptyDir: {}
        - name: multitenant-auth-nginx-conf
          configMap:
            name: multitenant-auth-nginx-config-map
