apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multitenant-auth
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
