apiVersion: batch/v1
kind: Job
metadata:
  namespace: multitenant-auth
  name: app-job
spec:
  template:
    spec:
      containers:
        - name: app-job
          image: localhost:32000/php-mt-auth-k8:latest
          command: ["php", "artisan", "migrate:fresh", "--seed"]
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config-map
      restartPolicy: Never
