apiVersion: v1
kind: Service
metadata:
  namespace: multitenant-ec
  name: db-service
  labels:
    app: db-service
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: db
