apiVersion: v1
kind: ConfigMap
metadata:
  namespace: multitenant-ec
  name: nginx-config-map
data:
  default.conf: |
    server {
        listen 80;
        index index.php index.html;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        root /var/www/public;
        client_max_body_size 120M;
        location ~ \.php$ {

             if ($request_method = 'OPTIONS') {
                add_header 'Cache-Control' 'private';
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Credentials' 'true';
                add_header 'Access-Control-Allow-Methods' 'POST, GET, OPTIONS, PUT, PATCH, DELETE';
                add_header 'Access-Control-Allow-Headers' '*, Authorization';
                add_header 'Access-Control-Expose-Headers' 'X-Pagination-Total,X-Pagination-Per-Page,X-Pagination-Current-Page,X-Pagination-From,X-Pagination-To,X-Pagination-Last-Page';
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }
    }
